### ISSUE TITLE
Set the "JWT_SECRET" environment variable

### ISSUE THREAD

**Issue by tbenst** [tzemanovic/haskell-yesod-realworld-example-app#4]
Hitting this error:
```
> export JWT_SECRET="some secret value"
> yesod devel
Success! Waiting for next file change.
Type help for available commands. Press enter to force a rebuild.
Starting devel application
devel.hs: Set the "JWT_SECRET" environment variable
Unexpected: child process exited with ExitFailure 1
```

If relevant, I did slightly modify the stack.yaml for use with Nix:
```
resolver: lts-14.25
packages:
- .
extra-deps:
- esqueleto-2.6.0
- jwt-0.9.0

install-ghc: false
system-ghc: true

nix:
  enable: true
  packages: [glpk, pcre, zlib]
```

**Comment by tzemanovic** [comment]
I think this is indeed caused by nix as it runs in a pure environment. You can either ask it to run in non-pure environment (add `pure: false` in stack.yaml, or run with `--no-nix-pure`), or set the variable via a custom shell.nix file. Please check out the [nix integration docs for stack](https://docs.haskellstack.org/en/stable/nix_integration/#the-nix-shell).

**Comment by tbenst** [comment]
Thanks!
